export const estimateTemplates = [
  ["simple_tv_wall", "Simple TV Wall", ["panels_standard", "tv_mount"]],
  ["tv_wall_lower_cabinet", "TV Wall with Lower Cabinet", ["panels_standard", "cabinet_short", "tv_mount"]],
  ["tv_wall_tall_side_cabinets", "TV Wall with Tall Side Cabinets", ["panels_standard", "cabinet_short", "cabinet_tall", "tv_mount"]],
  ["full_media_wall", "Full Media Wall with Cabinets and Shelves", ["panels_premium", "cabinet_short", "cabinet_tall", "shelves", "led", "tv_mount"]],
  ["den_room_panel_wall", "Den Room Panel Wall", ["panels_standard", "hidden_door"]],
  ["foyer_wall", "Foyer Wall", ["panels_premium", "mirror_standard"]],
  ["double_height_foyer", "Double-Height Foyer", ["panels_premium", "hidden_door", "lamp"]],
  ["foyer_ceiling", "Foyer Ceiling", ["panels_ceiling", "led"]],
  ["living_room_tv_wall", "Living Room TV Wall", ["panels_standard", "tv_stand", "tv_mount"]],
  ["living_room_corner_unit", "Living Room Corner Unit", ["panels_standard", "box_open_shelving"]],
  ["kitchen_wall_panels", "Kitchen Wall Panels", ["panels_standard", "led"]],
  ["kitchen_under_bar", "Kitchen Under Bar", ["under_bar_panels"]],
  ["guest_bedroom_back_wall", "Guest Bedroom Back Wall", ["panels_standard", "led"]],
  ["master_bedroom_tv_wall", "Master Bedroom TV Wall", ["panels_premium", "tv_stand", "cabinet_tall", "tv_mount"]],
  ["master_bedroom_bed_back_wall", "Master Bedroom Bed Back Wall", ["panels_premium", "console", "nightstand", "led"]],
  ["bathroom_vanity_wall", "Bathroom Vanity Wall", ["stone_look_panels", "mirror_standard", "led"]],
  ["master_bathroom_vanity", "Master Bathroom Vanity", ["stone_look_panels", "mirror_bronze", "cabinet_short", "led"]],
  ["hallway_panels", "Hallway Panels", ["panels_standard", "hidden_door"]],
  ["dining_bar", "Dining Bar", ["panels_premium", "console", "led"]],
  ["closet_sliding_doors", "Closet Sliding Doors", ["sliding_doors", "mirror_standard"]],
  ["closet_reface", "Closet Reface", ["closet_reface", "mirror_framed"]],
  ["office_murphy_bed", "Office Wall with Murphy Bed", ["murphy_bed", "shelves"]],
  ["office_desk", "Office Wall with Desk", ["desk", "shelves", "led"]],
  ["custom_wall", "Custom Wall", ["panels_standard"]],
].map(([id, name, catalogItems]) => ({
  id,
  name,
  catalogItems,
  publicSummary: `${name} with editable line items for CAS AURUM review.`,
  clientVisible: true,
  supportsImages: true,
}));
